### ISSUE TITLE
Buggy frightened ghosts

### ISSUE THREAD

**Issue by siew24** [siew24/Pacman-Demo#9]
Recently a new bug has appeared - ghosts aren't able to return to normal states after multiple power pellets have been eaten.

**Comment by LumpBloom7** [comment]
Hmm that's odd. Will investigate.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LumpBloom7** [comment]
It seems this line is the cause of the problem.
https://github.com/siew24/Pacman-Demo/blob/c3732b6be79088370b737df19c183d5fa2b04803/Test%20Bench/inc/Systems/PelletSystem.h#L43

If the ghost is already afraid, it'll override its actual previous state with `BehaviourModes::afraid`, resulting in an infinite afraid loop until eaten.
